### ISSUE TITLE
TextEncoder is not a constructor

### ISSUE THREAD

**Issue by larksoftware** [mazznoer/colorgrad-js#1]
I'm getting an error just importing this module, any ideas?

> Uncaught TypeError: TextEncoder is not a constructor

This is what I did.

```
npm init -y
npm install @mazznoer/colorgrad
npm install --save-dev parcel
```
I made an `index.html` that pulled in an `index.js`

--index.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>Colorgrad</title>

    <script src="index.js" type="module" />
  </head>
  <body>
    Colorgrad
  </body>
</html>
```

--index.js
```
import colorgrad from "@mazznoer/colorgrad";
```

Then I added a script in `package.json`
```
...
  "scripts": {
    "dev:watch": "parcel index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
...
```

Then `npm run dev:watch` and when I open the browser http://localhost:1234/ I get the error above in the console. Any ideas?

**Comment by Zolmok** [comment]
I have more information. I was attempting to run your example in the README.md

```javascript
import colorgrad from "@mazznoer/colorgrad";

let gradient = colorgrad.custom_gradient(["#C41189", "#00BFFF", "#FFD700"], null, "oklab", "linear");

// get the gradient domain min & max
console.log(gradient.domain()); // [0, 1]

// get single color at position 0.5
let hex = gradient.at(0.5).hex();

// get single color at position 0.75
let [r, g, b, a] = gradient.at(0.75).rgba8();

// get 100 colors evenly spaced along gradient
let colors = gradient.colors(100);

for (let c of colors) {
    console.log(c.hex());
}
```
when I ran into the TextEncoder problem.  However I found some scripst in your `examples` directory that ran fine. So I tried running the sample above at the command line and it also ran fine.  So I'm guessing that this library is intended for node only and not the browser, or there is a bug.  I was under the impression that it was intended for the browser because you compared it with `d3-scale`.  Is it supposed to run in a browser? Have you tried it?

**Comment by mazznoer** [comment]
I just published a new version (with new name too, for simplicity) `colorgrad-js`. And it now support not just for node, but for browser and bundler.

**Comment by larksoftware** [comment]
I can confirm it is working in the browser now, tyvm!
